
import { Inter } from 'next/font/google'
import './globals.css'
import MyContext  from './Helper.js/Context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',      //! Used for giving title to the webpage
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className}>
        <MyContext>{children}</MyContext>
      </body>
    </html>
  );
}
